using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cafe_AV.Models
{
    public class DbInitializer
    {
        public static void Seed(AppDbContext context)
        {

            if (!context.Categories.Any())
            {
                context.Categories.AddRange(Categories.Select(c => c.Value));
            }

            if (!context.Items.Any())
            {
                context.AddRange
                (
                   new Item { Name = "Veg Salt & Peeper", Price = 180, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false},
                   new Item { Name = "Com Salt & Peeper", Price = 180, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = true, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chilli Potato", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Honey Chilli Potato", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chilli Mushroom", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chilli Panner", Price = 220, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chilli Chap", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Veg Manchurian", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chilli Manchurian", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Potato 65", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Panner 65", Price = 220, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Mushroom Kurkure", Price = 220, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chiili Chicken", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chicken 65", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chicken Lollipop", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chicken Salt & Peeper", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Schezwan Chicken", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Crispy Honey Chicken", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Drums Of Heaven", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Lemon Chicken Dry", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chicken Schezwan Lolli", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Starter"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chiili Potato Hot Garlic Souce", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Gravy"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Veg Manchurian Gravy", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Gravy"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None , CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Panner Manchurian", Price = 220, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Gravy"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Mushroom Hot Garlic Souce", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Gravy"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chiili Panner Gravy", Price = 250, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Gravy"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chiili Mushroom Manchurian", Price = 250, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Veg Gravy"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Chiili Chicken Gravy", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Gravy"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Schezwan Chicken Gravy", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Gravy"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Lemon Chicken Gravy", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Non-Veg Gravy"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Tikka Masala", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Tikka Masala", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Palak", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Palak", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Kali Mirch", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Kali Mirch", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Tawa Masala", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Tawa Masala", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Chatpata", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Chatpata", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Palak", Price = 130, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Palak", Price = 230, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Kolhapuri", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Kolhapuri", Price = 240, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Kadhai", Price = 130, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Kadhai", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Bukhara", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Bukhara", Price = 250, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Mix Veg Handi", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Mix Veg Handi", Price = 240, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Garlic Mushroom Masala", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Garlic Mushroom Masala", Price = 250, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Mushroom Masala", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Mushroom Masala", Price = 240, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "mushroom Matar", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Mushroom Matar", Price = 240, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Gobhi Masala", Price = 130, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Gobhi Masala", Price = 220, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Hara Bhara Masala ", Price = 130, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Hara Bhara Masala", Price = 220, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = " Veg Chatpata", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = " Veg Chatpata", Price = 240, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Pindi Chana Masala", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Pindi Chana Masala ", Price = 240, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Soya Chaap Butter Masala", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Soya Chaap Butter Masala", Price = 240, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Panner Makkhan Wala", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Panner Makkhan Wala", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Do Pyaza", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Do Pyaza", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Lababdar", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Lababdar", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Corn Masala ", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Corn Masala", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Tadka Yellow", Price = 120, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Butter Masala", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Paneer Butter Masala", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Tadka Yellow", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Handi", Price = 130, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Handi", Price = 220, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Veg.Jalfarzi", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Veg.Jalfarzi", Price = 240, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Soya Chaap Tawa Masala", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Soya Chaap Tawa masala", Price = 240, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Green Peas Masala", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Green Peas Masala", Price = 240, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Aloo Gobhi", Price = 120, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Aloo Gobhi", Price = 220, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Malai Kofta", Price = 250, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Veg Kofta", Price = 250, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Jeera Aloo", Price = 120, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic" , UnitsInOrder = 0,Size= Size.Half, Discount = 20, Quantity="",Customise= false, CustomisedType= CustomisedType.None, CustomisedOption="",Discontinued=false},
                   new Item { Name = "Jeera Aloo", Price = 220, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Makhani", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                   new Item { Name = "Dal Makhani", Price = 250, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Rajama Masala", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Rajama  Masala", Price = 250, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Paneer Kadhai", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Paneer Kadhai", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Paneer Matar", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Paneer Matar", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Mix Veg", Price = 140, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Mix Veg", Price = 250, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Paneer Sahi", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Paneer Sahi", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chana Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chana Masala", Price = 240, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Dal Fry", Price = 130, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Dal Fry", Price = 260, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "",Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Lababdaar", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Lababdaar", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Sagwala Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Sagwala Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Hyderabadi", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Hyderabadi", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Handi Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Handi Masala", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Bhuna Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Bhuna Masala", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Tawa Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Tawa Masala", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Leg Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Leg Masala", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Handi", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Handi", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Korma", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Korma", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Rogan Josh", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Rogan Josh", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Kohlapuri", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Kohlapuri", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Kali Mirch", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Kali Mirch", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Chatpata", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Chatpata", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Mughlai", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Mughlai", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Lehsooni Dhaniya", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Lehsooni Dhaniya", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Desi Special Chicken", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Desi Special Chicken", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Lehsooni Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Lehsooni Masala", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Rara Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Rara Masala", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Seekh Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Seekh Masala", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Keema Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Keema Masala", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Cream", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Cream", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Mutton Curry", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Mutton Rogan Josh", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Mutton Do Pyaza", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Mutton Korma", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Mutton Kadhai", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Mutton Rara", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Mutton Masala", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Do Pyaza", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Do Pyaza", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Kadhai", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Kadhai", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Tikka Masala", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Tikka Masala", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Curry", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Curry", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Butter", Price = 300, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Half, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Butter", Price = 400, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Main Course Non-Vegetarian"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.Full, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Aloo Paratha", Price = 45, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Paratha"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType =CustomisedType.None , CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Gobhi Paratha", Price = 50, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Paratha"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Pyaz Paratha", Price = 45, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Paratha"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Pudina Paratha", Price = 40, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Paratha"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Mixed Paratha", Price = 50, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Paratha"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Ajwain Paratha", Price = 40, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Paratha"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Veg Noodles", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Paratha"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Veg Hakka Noodles", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Noodles & Rice"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Veg Singapuri Noodles", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Noodles & Rice"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chilli Garlic Noodles", Price = 170, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Noodles & Rice"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chilli Panner Noodles", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Noodles & Rice"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Schezwan Noodles", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Noodles & Rice"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Egg Noodles", Price = 180, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Noodles & Rice"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Noodles", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Noodles & Rice"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chilli Garlic Chicken Noodles", Price = 230, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Noodles & Rice"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Veg Roll", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Rolls"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Roll", Price = 220, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Rolls"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Panner Roll", Price = 200, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Rolls"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Egg Roll", Price = 250, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Rolls"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Egg Roll", Price = 180, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Chinese Rolls"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Veg Hot & Sour Soup", Price = 120, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Soups Veg"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Veg Manchow Soup", Price = 120, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Soups Veg"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Creamy Tomato Soup", Price = 120, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Soups Veg"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Sweet Corn Soup", Price = 120, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Soups Veg"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Creamy Mushroom Soup", Price = 120, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Soups Veg"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Veg Lemon Coriander Soup", Price = 120, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Soups Veg"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Creamy Chicken Soup", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Soups Non-Veg"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Hot & Sour Soup", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Soups Non-Veg"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Manchow Soup", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Soups Non-Veg"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Sweet Corn Soup", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Soups Non-Veg"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false },
                       new Item { Name = "Chicken Lemon Coriender Soup", Price = 150, shortDescription = "Snacks of India!", LongDescription = "Lorem Ipsum", Category = Categories["Soups Non-Veg"], InStock = true, isItemOfTheWeek = true, AllergyInformation = "Alergic", UnitsInOrder = 0, Size = Size.None, Discount = 20, Quantity = "", Customise = false, CustomisedType = CustomisedType.None, CustomisedOption = "", Discontinued = false }

                );
            }

            context.SaveChanges();
        }

        private static Dictionary<string, Category> categories;
        public static Dictionary<string, Category> Categories
        {
            get
            {
                if (categories == null)
                {
                    var genresList = new Category[]
                    {
                        new Category { CategoryName = "BestSellers" },
                        new Category { CategoryName = "Chinese Veg Starter" },
                        new Category { CategoryName = "Chinese Non-Veg Starter"},
                        new Category { CategoryName = "Chinese Veg Gravy"},
                        new Category { CategoryName = "Chinese Non-Veg Gravy"},
                        new Category { CategoryName = "Main Course Vegetarian"},
                        new Category { CategoryName = "Main Course Non-Vegetarian"},
                        new Category { CategoryName = "Paratha"},
                        new Category { CategoryName = "Chinese Noodles & Rice"},
                        new Category { CategoryName = "Chinese Rolls"},
                        new Category { CategoryName = "Soups Veg"},
                        new Category { CategoryName = "Soups Non-Veg"}
                    };

                    categories = new Dictionary<string, Category>();

                    foreach (Category genre in genresList)
                    {
                        categories.Add(genre.CategoryName, genre);
                    }
                }

                return categories;
            }
        }
    }
}

